# DEPRECATED: This template has been superseded by flow-logs-s3.yml
# Please use flow-logs-s3.yml instead, which provides the same functionality
# without requiring AWS Organizations or cross-account configuration.

AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy an S3 bucket in the security tools account that allows
  any account in the organization to write VPC Flow Logs.
Parameters:
  AWSOrganizationId:
    Description: The ID number of the parent account owning the flow logs you want to receive.
    Type: String
    Default: "o-ck6nmvfrcc"
  ForeignAccountRetention:
    Description: The number of days flows should be retained in the Foreign Account s3 storage before expiry.
    Type: String
    Default: "90"
  ForeignAccountGlacierRetention:
    Description: The number of days flows should be retained in the Foreign Account glacier storage before expiry.
    Type: String
    Default: "365"
  ObjectLock:
    Description: Lock objects at the Cloud provider level disallowing tampering.  This can only be done on create.  Never updatable.
    Type: String
    AllowedValues: 
      - True
      - False
    Default: False
Resources:
  ForeignAccountS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        'Fn::Sub': 'organization-flow-logs.${AWS::Region}.${AWS::AccountId}'
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerPreferred
      ObjectLockEnabled: !Ref ObjectLock
      LifecycleConfiguration:
        Rules:
          - Id: "Expire"
            Status: "Enabled"
            ExpirationInDays: !Ref ForeignAccountRetention # Complete Disposal/Deletion of Data after 90 days with the exception of glacier.
          - Id: GlacierRule
            Prefix: glacier
            Status: Enabled
            ExpirationInDays: !Ref ForeignAccountGlacierRetention
            Transitions:
              - Days: 1
                StorageClass: GLACIER
      VersioningConfiguration:
        Status: Enabled
    DeletionPolicy: Retain
  BucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: 
        Ref: ForeignAccountS3Bucket
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: "AWSFlowAclCheck"
            Effect: "Allow"
            Principal: 
              Service: "delivery.logs.amazonaws.com"
            Action: "s3:GetBucketAcl"
            Resource: 
              !Sub |-
                arn:aws:s3:::${ForeignAccountS3Bucket}
          - 
            Sid: "AWSFlowLogWrite"
            Effect: "Allow"
            Principal: 
              Service: "delivery.logs.amazonaws.com"
            Action: "s3:PutObject"
            Resource: 
              - !Sub arn:aws:s3:::${ForeignAccountS3Bucket}/AWSLogs/${AWSOrganizationId}/*
              - !Sub arn:aws:s3:::${ForeignAccountS3Bucket}/AWSLogs/*
            Condition: 
              StringEquals:
                s3:x-amz-acl: "bucket-owner-full-control"
Outputs:
  BucketName:
    Description: The name of the s3 bucket in this account that will be storing cloudtrail log data.
    Value: !Ref ForeignAccountS3Bucket
